### ISSUE TITLE
Packet encoder error

### ISSUE THREAD

**Issue by InvixYT** [PaperMC/Travertine#100]
[18:23:48 WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0xa958ff72, L:/172.18.0.11:20012 ! R:/98.13.86.200:38352]
java.util.NoSuchElementException: packet-encoder
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at us.myles.ViaVersion.bungee.handlers.BungeeChannelInitializer.initChannel(BungeeChannelInitializer.java:37) ~[?:?]
at us.myles.ViaVersion.bungee.handlers.BungeeChannelInitializer.initChannel(BungeeChannelInitializer.java:11) ~[?:?]
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:427) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:d34de8a:86]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

This is the error i keep getting

**Comment by electronicboy** [comment]
Update your plugins, especially the Via ones.

**Comment by InvixYT** [comment]
what do you mean the Via ones?

**Comment by electronicboy** [comment]
`us.myles.ViaVersion.bungee.handlers.BungeeChannelInitializer.initChannel(BungeeChannelInitializer.java:37) ~[?:?]`

**Comment by InvixYT** [comment]
ahhh thats because viaversion doesnt support travertine

**Comment by electronicboy** [comment]
ViaVersion works fine with travertine, outdated versions of ViaVersion do not. The protocol support that Travertine provides for 1.7.x is irrelevant to ViaVersion

**Comment by InvixYT** [comment]
Thats weird cause my viaversion is updated and the error is going on.

**Comment by creeper123123321** [comment]
Are you using the jar from https://ci.viaversion.com/view/ViaVersion/ ?

**Comment by InvixYT** [comment]
No just from the spigot
