### ISSUE TITLE
antibot stopped working

### ISSUE THREAD

**Issue by kamziksvk** [PaperMC/Travertine#121]
Hello, our antibot stopped working with the latest release of your Travertine. Here is the pastebin info:
```
[04:02:40] [main/WARN]: Exception encountered when loading plugin: AntiBotDeluxe
java.lang.IllegalAccessError: tried to access class net.md_5.bungee.api.plugin.PluginClassloader from class de.fusion.antibotdeluxe.bungee.AntiBotDeluxe
	at de.fusion.antibotdeluxe.bungee.AntiBotDeluxe.onEnable(AntiBotDeluxe.java:180) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:296) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
```

**Comment by mikroskeem** [comment]
https://github.com/SpigotMC/BungeeCord/commit/f41b1fc82131842409fed2df1c702cda36b06bd2

Tell your plugin's author to fix the plugin.
