### ISSUE TITLE
Json messages not working

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Travertine#135]
```
[12:58:05] [Netty Worker IO Thread #29/INFO]: merinos executed command: /fr bmsg FIVEFIVE
[12:58:05] [BFriend Pool Thread #0/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@221a1bb, id=195, owner=at.yawk.bfriend.BFriend@25fc83c2, task=at.yawk.bfriend.BFriend$FriendCommand$$Lambda$441/417352248@26e3de68, delay=0, period=0, running=true) encountered an exception
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at uk.co.thinkofdeath.command.CommandManager.execute(CommandManager.java:500) ~[?:?]
	at uk.co.thinkofdeath.command.CommandManager.execute(CommandManager.java:423) ~[?:?]
	at at.yawk.bfriend.BFriend$FriendCommand.lambda$execute$1(BFriend.java:255) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at uk.co.thinkofdeath.command.CommandManager.execute(CommandManager.java:494) ~[?:?]
	... 6 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "Respond"
	at com.google.gson.Gson.fromJson(Gson.java:899) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:90) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:58) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:58) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at at.yawk.bfriend.Handler.lambda$format$0(Handler.java:58) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
	at at.yawk.bfriend.Handler.format(Handler.java:59) ~[?:?]
	at at.yawk.bfriend.Handler.broadcast(Handler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at uk.co.thinkofdeath.command.CommandManager.execute(CommandManager.java:494) ~[?:?]
	... 6 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: "Respond"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:21) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:12) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:90) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:58) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:58) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:102) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57) ~[bungee.jar:git:Travertine-Bootstrap:1.16-R0.2-SNAPSHOT:8d51590:150]
	at at.yawk.bfriend.Handler.lambda$format$0(Handler.java:58) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
	at at.yawk.bfriend.Handler.format(Handler.java:59) ~[?:?]
	at at.yawk.bfriend.Handler.broadcast(Handler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at uk.co.thinkofdeath.command.CommandManager.execute(CommandManager.java:494) ~[?:?]
	... 6 more
```

**Comment by electronicboy** [comment]
Should be fixed in the upcoming build
