### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by assasin541** [PaperMC/Travertine#143]
ERROR StatusLogger Catching
 java.net.SocketException: No such device (getFlags() failed)
        at java.net.NetworkInterface.isLoopback0(Native Method)
        at java.net.NetworkInterface.isLoopback(NetworkInterface.java:411)
        at org.apache.logging.log4j.core.util.NetUtils.isUpAndNotLoopback(NetUtils.java:134)
        at org.apache.logging.log4j.core.util.NetUtils.getMacAddress(NetUtils.java:99)
        at org.apache.logging.log4j.core.util.UuidUtil.<clinit>(UuidUtil.java:67)
        at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:53)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:135)
        at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
        at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:79)
        at org.apache.logging.log4j.core.async.AsyncLoggerContextSelector.createContext(AsyncLoggerContextSelector.java:46)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:228)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)

**Comment by electronicboy** [comment]
This is an environmental issue, oddball network configuration?
As this is not harmful, I'd just say ignore it, otherwise, you'd need to look into sending an issue report for log4j.

**Comment by assasin541** [comment]
@electronicboy what issue? Why does it show?

**Comment by electronicboy** [comment]
log4j blew up trying to get the MAC address from your network interface, apparently some network interface it found did not exist or something

**Comment by assasin541** [comment]
@electronicboy how to fix that?
