### ISSUE TITLE
Error. I got this error!

### ISSUE THREAD

**Issue by PiiSaba** [PaperMC/Travertine#79]
[14:34:34 ERROR]: [/182.164.187.133:53852|WKSK109] <-> DownstreamBridge <-> [UHCFFA] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:
 
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:69) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 8192))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:40) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:486f54b:62]
    ... 27 more
[14:34:34 INFO]: [YouTube0099] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by electronicboy** [comment]
Either the client or the server sent an invalid packet, this is often caused by plugins which modify the data sent to a client, or mods which aren't sending packets properly
