### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected packet received during login process

### ISSUE THREAD

**Issue by minecraft7net** [PaperMC/Travertine#83]
Travertine-b69.jar

today i saw some errors on Travetine - it may be a type of attack or known error or potential bug?

this sentence i have with small timeframe from couple of different ip addresses 
"..."
4554202f726f626f74732e74787420485454502f312e310d0a486f73743a20706c616e6574637261667467616d65732e6e65743a32353536350d0a436f6e6e65
"..."

https://pastebin.com/XHUMWpak

"..."
[07:19:14] [Netty Worker IO Thread #7/ERROR]: [/5.255.250.139:20166] <-> InitialHandler - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during login process!
4554202f726f626f74732e74787420485454502f312e310d0a486f73743a20706c616e6574637261667467616d65732e6e65743a32353536350d0a436f6e6e65
        at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:146) ~[Travertine-b69.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:43bf43a:69]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[Travertine-b69.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:43bf43a:69]

"..."

https://pastebin.com/ZkWRQsGU

**Comment by DoNotSpamPls** [comment]
This is not a problem with Travertine, but with BungeeCord itself.
Related: SpigotMC/BungeeCord#2535

**Comment by minecraft7net** [comment]
OK after additional - "test".

my case is just a webbrowser connection to bungee and it can be reproduce by connection from firefox to IP:25565

its my connection from firefox.
"..."
java.lang.IllegalArgumentException: Unexpected packet received during login process!
4554202f20485454502f312e310d0a486f73743a20706c616e6574637261667467616d65732e6e65743a32353536350d0a557365722d4167656e743a204d6f7a
at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:146) ~[Travertine-b69.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:43bf43a:69]
"..."

so probably solution is to create additional "something" on haproxy to redirect HTTP/HTTPS connections.
