### ISSUE TITLE
1.7.x players get kicked with proxy error when 1.8.x player connects

### ISSUE THREAD

**Issue by DrayGH** [PaperMC/Travertine#86]
Getting this error in console when a 1.8.x player joins a server with 1.7.x players online on a 1.7.x-1.8.x compat server: 

[io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@2192c39f
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
	at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:529) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at net.md_5.bungee.UserConnection.init(UserConnection.java:170) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:544) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:4be0216:77]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by electronicboy** [comment]
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:529) ~
```
Your configuration file is invalid, please seek support on the forums/IRC/Discord
