### ISSUE TITLE
1.9.x-1.12.x+ players unable to join hub due to travertine (Team viaversion already exists in this scoreboard)

### ISSUE THREAD

**Issue by TMCGH** [PaperMC/Travertine#92]
Hello, my customized spigot jar is able to handle protocol logins from 1.7.x-1.12.x ; I tested this jars capability to accept all versions on my own server ran on my localhost pc and everything worked fine regarding accepting logins from all versions.. but when when I put this spigot jar on the hub server on my travertine ran network, I get this error when someone 1.9.x+ tries to connect:

tldr; my custom spigot jar accepts 1.7.x-1.12.x (tested+confirmed on localhost), dosnt work on servers ran with travertine

[18:25:40] [Netty Worker IO Thread #13/ERROR]: [/REDACTED|Player] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IllegalArgumentException: Team viaversion already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:217) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:172) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:25:40] [Netty Worker IO Thread #13/INFO]: [Player] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by electronicboy** [comment]
if you're not getting this while switching servers, your server somehow managed to send the scoreboard team twice, I don't recall if the client itself considers this an error as bungee does

If this is only while you're switching servers, this is a known BungeeCord issue (and ViaVersion themselves have patched this in their own server, you'd need to get your fork to update the code)

**Comment by PSNRigner** [comment]
Has been fixed by upgrading viaversion. Can be closed.
